# Generated by Django 4.2.8 on 2024-01-05 22:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='billetera',
            fields=[
                ('id_b', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('capital', models.FloatField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='cuenta',
            fields=[
                ('id_c', models.AutoField(primary_key=True, serialize=False)),
                ('banco', models.CharField(max_length=20)),
                ('capital', models.FloatField(max_length=6)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(default='corriente', max_length=10)),
                ('interes', models.FloatField(default=0.0, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='transaccion',
            fields=[
                ('id_t', models.AutoField(primary_key=True, serialize=False)),
                ('retiro', models.FloatField(default=0, max_length=6)),
                ('Abono', models.FloatField(default=0, max_length=6)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2024, 1, 5, 16, 45, 29, 926338))),
                ('id_bill', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CuentaBancaria.billetera')),
                ('id_c', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CuentaBancaria.cuenta')),
            ],
        ),
    ]
