# Generated by Django 4.2.8 on 2023-12-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuenta',
            fields=[
                ('id_c', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('banco', models.CharField(max_length=20)),
                ('capital', models.FloatField(max_length=6)),
                ('retiro', models.FloatField(max_length=6)),
                ('Abono', models.FloatField(max_length=6)),
            ],
        ),
    ]
