# Generated by Django 4.2.6 on 2024-01-11 02:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaBancaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billetera',
            name='id_tr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CuentaBancaria.transaccion'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 20, 24, 2, 4997)),
        ),
    ]
