# Generated by Django 4.2.8 on 2023-12-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaBancaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='operacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('retiro', models.FloatField(max_length=6)),
                ('Abono', models.FloatField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='Abono',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='retiro',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(default='corriente', max_length=10),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='id_c',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
