# Generated by Django 4.2.8 on 2024-01-05 22:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaBancaria', '0002_alter_transaccion_fecha_alter_transaccion_id_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 16, 55, 30, 153496)),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='id_c',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CuentaBancaria.cuenta'),
        ),
    ]
