# Generated by Django 4.2.6 on 2024-01-11 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaBancaria', '0002_alter_billetera_id_tr_alter_transaccion_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billetera',
            name='capital',
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 20, 24, 56, 304935)),
        ),
    ]
