# Generated by Django 4.2.8 on 2023-12-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaBancaria', '0002_operacion_remove_cuenta_abono_remove_cuenta_retiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='interes',
            field=models.FloatField(default=0.0, max_length=6),
        ),
    ]
