# Generated by Django 4.2.8 on 2024-01-05 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaBancaria', '0003_remove_efectivo_id_cta_efectivo_id_trans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.date(2024, 1, 5)),
        ),
    ]
