# Generated by Django 4.2.8 on 2024-01-06 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaBancaria', '0003_alter_transaccion_fecha_alter_transaccion_id_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billetera',
            name='id_b',
            field=models.AutoField(default=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 18, 16, 21, 21118)),
        ),
    ]
