# Generated by Django 4.2.8 on 2023-12-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaBancaria', '0003_cuenta_interes'),
    ]

    operations = [
        migrations.CreateModel(
            name='montoefectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='operacion',
            new_name='transaccion',
        ),
    ]
