# Generated by Django 4.2.8 on 2023-12-30 23:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaBancaria', '0004_montoefectivo_rename_operacion_transaccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='efectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.FloatField(max_length=6)),
                ('id_cta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuentaBancaria.cuenta')),
            ],
        ),
        migrations.DeleteModel(
            name='montoefectivo',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='id',
            new_name='id_t',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 12, 30)),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='id_c',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CuentaBancaria.cuenta'),
        ),
    ]
