# Generated by Django 4.2.6 on 2024-01-11 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaBancaria', '0004_alter_transaccion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='billetera',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 21, 39, 23, 385063)),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 21, 39, 23, 385063)),
        ),
    ]
