# Generated by Django 4.2.8 on 2024-01-06 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaBancaria', '0004_alter_billetera_id_b_alter_transaccion_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='capital',
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 20, 58, 24, 365864)),
        ),
    ]
