# Generated by Django 4.2.8 on 2024-01-05 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaBancaria', '0004_alter_transaccion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 7, 53, 5, 449212)),
        ),
    ]
