# Generated by Django 4.2.6 on 2024-01-11 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaBancaria', '0005_billetera_fecha_alter_transaccion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billetera',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 22, 11, 43, 124995)),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 22, 11, 43, 123994)),
        ),
    ]
