# Generated by Django 4.2.8 on 2024-01-06 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaBancaria', '0005_remove_cuenta_capital_alter_transaccion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='descripcion',
            field=models.CharField(default='transaccion por compra', max_length=30),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 10, 12, 27, 151942)),
        ),
    ]
