# Generated by Django 4.2.6 on 2024-01-05 21:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaBancaria', '0005_alter_transaccion_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='billetera',
            fields=[
                ('id_b', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('capital', models.FloatField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='efectivo',
            name='id',
        ),
        migrations.AddField(
            model_name='efectivo',
            name='id_m',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 15, 15, 46, 814891)),
        ),
        migrations.AddField(
            model_name='efectivo',
            name='id_b',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CuentaBancaria.billetera'),
        ),
    ]
