# Generated by Django 4.2.8 on 2024-01-07 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaBancaria', '0006_transaccion_descripcion_alter_transaccion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='descripcion',
            field=models.CharField(default='No especificada', max_length=30),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 7, 4, 57, 141424)),
        ),
    ]
