# Generated by Django 4.2.8 on 2024-01-05 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaBancaria', '0006_billetera_remove_efectivo_id_efectivo_id_m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 15, 30, 18, 637790)),
        ),
    ]
