# Generated by Django 4.2.8 on 2024-01-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='cantidad',
            field=models.FloatField(max_length=0),
        ),
    ]
