# Generated by Django 4.2.8 on 2024-01-01 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='descripcion',
        ),
    ]
