# Generated by Django 4.2.6 on 2024-01-11 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaBancaria', '0004_alter_transaccion_fecha'),
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='id_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CuentaBancaria.billetera'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='id_transaccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CuentaBancaria.transaccion'),
        ),
    ]
