# Generated by Django 4.2.8 on 2023-12-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiales',
            name='cantidad',
        ),
    ]
