# Generated by Django 4.2.8 on 2023-12-30 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaBancaria', '0004_montoefectivo_rename_operacion_transaccion'),
        ('materiales', '0002_remove_materiales_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=25)),
                ('tipo', models.CharField(max_length=20)),
                ('precio_unitario', models.FloatField(max_length=6)),
                ('id_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuentaBancaria.cuenta')),
            ],
        ),
        migrations.DeleteModel(
            name='materiales',
        ),
    ]
