# Generated by Django 4.2.6 on 2024-01-11 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_compra_id_b_alter_compra_id_transaccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='id_b',
            new_name='id_bill',
        ),
    ]
