# Generated by Django 4.2.8 on 2023-12-30 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaBancaria', '0005_efectivo_delete_montoefectivo_and_more'),
        ('materiales', '0003_compra_delete_materiales'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='id_efec',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CuentaBancaria.efectivo'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='id_cuenta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CuentaBancaria.cuenta'),
        ),
    ]
