# Generated by Django 4.2.8 on 2024-01-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_compra_cantid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='cantid',
        ),
        migrations.AddField(
            model_name='compra',
            name='cantidad',
            field=models.IntegerField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='compra',
            name='descripcion',
            field=models.CharField(default='No insertada', max_length=25),
        ),
    ]
