# Generated by Django 4.2.8 on 2024-01-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0004_remove_compra_cantid_compra_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='id_efec',
        ),
    ]
