# Generated by Django 4.2.8 on 2024-01-05 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaBancaria', '0003_remove_efectivo_id_cta_efectivo_id_trans_and_more'),
        ('materiales', '0005_remove_compra_id_efec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='id_cuenta',
        ),
        migrations.AddField(
            model_name='compra',
            name='id_transaccion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CuentaBancaria.transaccion'),
        ),
    ]
