# Generated by Django 4.2.6 on 2024-01-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0006_remove_compra_id_cuenta_compra_id_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
